pipeline {
    agent any

    parameters {
        string(name: 'TOPIC_NAME', defaultValue: 'DevOps', description: 'Topics to learn')
        string(name: 'TARGET', defaultValue: 'Dream-Work', description: 'Target goal')
    }

    stages {
        stage('Call Script') {
            steps {
                sh 'chmod +x sayhello.sh'
                sh 'sayhello.sh ${TOPIC_NAME} ${TARGET}'
            }
        }
    }
}